github:
  client:
    id: eff356635bf6f6d97aba
    secret: 49cdadb9bca561c9bf315976579f722a319de898
  redirect:
    uri: http://47.112.126.105:81/community/callback
qiniu:
  oss:
    accessKey: 2Ib66pCbhytfZreY7HuafdZ1ULyGRjofo5PL7NjX
    secretKey: _q_VYTjpntTVXRuVUePKxK7DuOQcC5M_9U_rKnlV
    bucket: acommunity
spring:
  servlet:
    multipart:
      #单个文件的最大限制
      max-file-size: 100MB
      #单次上传文件的最大限制
      max-request-size: 1000MB
  thymeleaf:
    #thymeleaf关闭缓存
    cache: false
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://rm-wz9vg8cz3x55p87r0125010.mysql.rds.aliyuncs.com:3306/community?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    schema:
    #      - classpath:department.sql
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池配置
      # 配置初始化大小、最小、最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 3000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,slf4j
      # 配置web监控,默认配置也和下面相同(除用户名密码，enabled默认false外)，其他可以不配
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: root
        allow: 127.0.0.1
#数据库连接
#h2
#  datasource:
#    url: jdbc:h2:D:\Works\Practice\Java\Web Project\Spring boot\community\db\community
#    username: sa
#    password: 123
#    driver-class-name: org.h2.Driver

server:
  port: 81
  servlet:
    context-path: /community

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.community.model
  mapper-locations: classpath:mapper/*.xml


pagehelper:
  helper-dialect: h2 #数据库方言
  reasonable: true #分页合理化
  support-methods-arguments: true #是否支持接口参数来传递分页参数，默认false
  page-size-zero: false #当设置为true的时候，如果pagesize设置为0（或RowBounds的limit=0），就不执行分页，返回全部结果
logging:
  file:
    name: log/community.log
  level:
    root: info